# Generated by Django 5.0.2 on 2024-03-07 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="jira_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="public_id",
            field=models.UUIDField(
                default=uuid.UUID("768bab25-5674-4277-b3ef-a916eb591dd6"), unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(
                default=uuid.UUID("da159017-7752-4d44-9821-c5f287d75927"), unique=True
            ),
        ),
    ]
