# Generated by Django 5.0.2 on 2024-03-07 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_jira_id_task_public_id_alter_user_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
