# Generated by Django 5.0.2 on 2024-02-26 22:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('9f80d92a-9176-42a4-80b3-db5efc377f72'), unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('accountant', 'accountant'), ('dev', 'dev'), ('lead', 'lead'), ('qa', 'qa')], default='dev', max_length=128),
        ),
    ]
