# Generated by Django 5.0.2 on 2024-02-29 17:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_public_id_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(
                default=uuid.UUID("c8629561-d79b-4ac4-940b-344c6468764b"), unique=True
            ),
        ),
    ]
